# Generated by Django 5.2.11 on 2026-05-16 15:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("examples", "0001_initial"),
        ("templates_library", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoverLetterExample",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="slug"
                    ),
                ),
                (
                    "job_title",
                    models.CharField(max_length=255, verbose_name="job title"),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("entry", "Entry Level"),
                            ("mid", "Mid Level"),
                            ("senior", "Senior Level"),
                        ],
                        max_length=10,
                        verbose_name="experience level",
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full cover letter content stored as structured JSON.",
                        verbose_name="content",
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="examples/cover-letters/previews/",
                        verbose_name="preview image",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="meta title",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, default="", verbose_name="meta description"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is featured"
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="views count"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cover_letter_examples",
                        to="examples.examplecategory",
                        verbose_name="category",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cover_letter_examples",
                        to="templates_library.documenttemplate",
                        verbose_name="template",
                    ),
                ),
            ],
            options={
                "verbose_name": "cover letter example",
                "verbose_name_plural": "cover letter examples",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
    ]
