# Generated by Django 5.2.11 on 2026-05-16 15:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_marketing",
                    models.BooleanField(
                        default=True,
                        help_text="Receive marketing and promotional emails.",
                        verbose_name="email marketing",
                    ),
                ),
                (
                    "email_product_updates",
                    models.BooleanField(
                        default=True,
                        help_text="Receive emails about product updates and new features.",
                        verbose_name="email product updates",
                    ),
                ),
                (
                    "email_tips",
                    models.BooleanField(
                        default=True,
                        help_text="Receive resume writing tips and career advice emails.",
                        verbose_name="email tips",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification preference",
                "verbose_name_plural": "notification preferences",
                "db_table": "notifications_preference",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("email_verification", "Email Verification"),
                            ("welcome", "Welcome"),
                            ("password_reset", "Password Reset"),
                            ("trial_reminder", "Trial Reminder"),
                            ("subscription_confirmed", "Subscription Confirmed"),
                            ("download_ready", "Download Ready"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="notification type",
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="subject")),
                (
                    "body",
                    models.TextField(
                        help_text="The notification message body (HTML or plain text).",
                        verbose_name="body",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is read"
                    ),
                ),
                (
                    "is_sent",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is sent"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="sent at"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "db_table": "notifications_notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="idx_notif_user_created"
                    ),
                    models.Index(
                        fields=["user", "is_read"], name="idx_notif_user_read"
                    ),
                ],
            },
        ),
    ]
