# Generated by Django 5.2.11 on 2026-05-16 15:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("templates_library", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CV",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=255, verbose_name="slug"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("complete", "Complete"),
                            ("downloaded", "Downloaded"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full CV content as JSON. Supports academic sections: publications, conferences, research, teaching, grants, etc.",
                        verbose_name="content",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Display and formatting settings.",
                        verbose_name="settings",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        db_index=True,
                        default="en-us",
                        max_length=10,
                        verbose_name="language",
                    ),
                ),
                (
                    "downloads_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="downloads count"
                    ),
                ),
                (
                    "last_edited",
                    models.DateTimeField(auto_now=True, verbose_name="last edited"),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cvs",
                        to="templates_library.documenttemplate",
                        verbose_name="template",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cvs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "CV",
                "verbose_name_plural": "CVs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CVDownload",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("docx", "DOCX"), ("txt", "TXT")],
                        max_length=10,
                        verbose_name="format",
                    ),
                ),
                (
                    "file_url",
                    models.URLField(
                        blank=True, max_length=1024, verbose_name="file URL"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="file size (bytes)"
                    ),
                ),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="cvs.cv",
                        verbose_name="CV",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cv_downloads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "CV download",
                "verbose_name_plural": "CV downloads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CVSection",
            fields=[
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="order"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("summary", "Summary"),
                            ("experience", "Experience"),
                            ("education", "Education"),
                            ("skills", "Skills"),
                            ("languages", "Languages"),
                            ("certificates", "Certificates"),
                            ("projects", "Projects"),
                            ("awards", "Awards"),
                            ("volunteer", "Volunteer"),
                            ("hobbies", "Hobbies"),
                            ("publications", "Publications"),
                            ("conferences", "Conferences"),
                            ("research", "Research"),
                            ("teaching", "Teaching"),
                            ("grants", "Grants"),
                            ("custom", "Custom"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="section type",
                    ),
                ),
                (
                    "content",
                    models.JSONField(blank=True, default=dict, verbose_name="content"),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="is visible"),
                ),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="cvs.cv",
                        verbose_name="CV",
                    ),
                ),
            ],
            options={
                "verbose_name": "CV section",
                "verbose_name_plural": "CV sections",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CVVersion",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(verbose_name="version number"),
                ),
                (
                    "content",
                    models.JSONField(blank=True, default=dict, verbose_name="content"),
                ),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="cvs.cv",
                        verbose_name="CV",
                    ),
                ),
            ],
            options={
                "verbose_name": "CV version",
                "verbose_name_plural": "CV versions",
                "ordering": ["-version_number"],
            },
        ),
        migrations.AddIndex(
            model_name="cv",
            index=models.Index(fields=["user", "status"], name="cv_user_status_idx"),
        ),
        migrations.AddIndex(
            model_name="cv",
            index=models.Index(
                fields=["user", "-created_at"], name="cv_user_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cv",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("user", "slug"),
                name="unique_cv_slug_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="cvversion",
            constraint=models.UniqueConstraint(
                fields=("cv", "version_number"), name="unique_cv_version_number"
            ),
        ),
    ]
