apiVersion: v1
kind: Service
metadata:
  name: resumer-frontend
  namespace: resumer
  labels:
    app.kubernetes.io/name: resumer-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: resumer-platform
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: resumer-frontend
    app.kubernetes.io/component: frontend
