apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: resumer-api-hpa
  namespace: resumer
  labels:
    app.kubernetes.io/name: resumer-api
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: resumer-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: resumer-api
  minReplicas: 3
  maxReplicas: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
