# Generated by Django 5.2.11 on 2026-05-16 15:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="The uploaded file.",
                        upload_to="media_library/files/%Y/%m/",
                        verbose_name="file",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Auto-generated thumbnail (images only).",
                        null=True,
                        upload_to="media_library/thumbnails/%Y/%m/",
                        verbose_name="thumbnail",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Alternative text for accessibility.",
                        max_length=255,
                        verbose_name="alt text",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("document", "Document"),
                            ("avatar", "Avatar"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="file type",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="The original name of the uploaded file.",
                        max_length=500,
                        verbose_name="original filename",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        help_text="File size in bytes.", verbose_name="file size"
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Image width in pixels (images only).",
                        null=True,
                        verbose_name="width",
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Image height in pixels (images only).",
                        null=True,
                        verbose_name="height",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="uploaded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "media file",
                "verbose_name_plural": "media files",
                "db_table": "media_library_file",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["file_type"], name="idx_media_file_type"),
                    models.Index(fields=["uploaded_by"], name="idx_media_uploaded_by"),
                ],
            },
        ),
    ]
