# Generated by Django 5.2.11 on 2026-05-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True, max_length=128, unique=True, verbose_name="ключ"
                    ),
                ),
                ("value", models.JSONField(default=dict, verbose_name="значение")),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Доступен через публичный API без авторизации.",
                        verbose_name="публичный",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
            ],
            options={
                "verbose_name": "системная настройка",
                "verbose_name_plural": "системные настройки",
                "db_table": "system_configuration",
                "ordering": ["key"],
            },
        ),
    ]
