# Generated by Django 5.2.11 on 2026-05-16 15:58

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user has verified their email.",
                        verbose_name="verified",
                    ),
                ),
                (
                    "is_premium",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user has an active premium subscription.",
                        verbose_name="premium",
                    ),
                ),
                (
                    "premium_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Premium subscription expiration date.",
                        null=True,
                        verbose_name="premium until",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en-us", "English (US)"),
                            ("en-gb", "English (UK)"),
                            ("en-in", "English (IN)"),
                            ("de", "Deutsch"),
                            ("fr", "Français"),
                            ("es", "Español"),
                            ("it", "Italiano"),
                            ("pt-br", "Português (BR)"),
                            ("ru", "Русский"),
                            ("tr", "Türkçe"),
                            ("uz", "Oʻzbekcha"),
                        ],
                        db_index=True,
                        default="en-us",
                        max_length=10,
                        verbose_name="language",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="country"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        blank=True,
                        default="UTC",
                        max_length=63,
                        verbose_name="timezone",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default="",
                        upload_to="avatars/%Y/%m/",
                        verbose_name="avatar",
                    ),
                ),
                (
                    "is_2fa_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether two-factor authentication is enabled.",
                        verbose_name="2FA enabled",
                    ),
                ),
                (
                    "totp_secret",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Base32-encoded TOTP secret key.",
                        max_length=64,
                        verbose_name="TOTP secret",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="last login IP"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "db_table": "accounts_user",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        unique=True,
                        verbose_name="token",
                    ),
                ),
                ("is_used", models.BooleanField(default=False, verbose_name="used")),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=apps.accounts.models._default_email_verification_expiry,
                        verbose_name="expires at",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "email verification",
                "verbose_name_plural": "email verifications",
                "db_table": "accounts_email_verification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="user agent"),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("desktop", "Desktop"),
                            ("mobile", "Mobile"),
                            ("tablet", "Tablet"),
                        ],
                        db_index=True,
                        default="desktop",
                        max_length=10,
                        verbose_name="device type",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="country"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "login history entry",
                "verbose_name_plural": "login history",
                "db_table": "accounts_login_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OAuthConnection",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("google", "Google"),
                            ("linkedin", "LinkedIn"),
                            ("github", "GitHub"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="provider",
                    ),
                ),
                (
                    "provider_uid",
                    models.CharField(max_length=255, verbose_name="provider UID"),
                ),
                (
                    "access_token",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Encrypted OAuth access token.",
                        verbose_name="access token (encrypted)",
                    ),
                ),
                (
                    "refresh_token",
                    models.TextField(
                        blank=True, default="", verbose_name="refresh token"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_connections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "OAuth connection",
                "verbose_name_plural": "OAuth connections",
                "db_table": "accounts_oauth_connection",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PasswordReset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        unique=True,
                        verbose_name="token",
                    ),
                ),
                ("is_used", models.BooleanField(default=False, verbose_name="used")),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=apps.accounts.models._default_password_reset_expiry,
                        verbose_name="expires at",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_resets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "password reset",
                "verbose_name_plural": "password resets",
                "db_table": "accounts_password_reset",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="idx_user_email"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["is_premium"], name="idx_user_premium"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["is_verified"], name="idx_user_verified"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["language"], name="idx_user_language"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["country"], name="idx_user_country"),
        ),
        migrations.AddIndex(
            model_name="loginhistory",
            index=models.Index(
                fields=["user", "-created_at"], name="idx_login_user_date"
            ),
        ),
        migrations.AddIndex(
            model_name="oauthconnection",
            index=models.Index(
                fields=["user", "provider"], name="idx_oauth_user_provider"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="oauthconnection",
            unique_together={("provider", "provider_uid")},
        ),
    ]
