# Generated by Django 5.2.11 on 2026-05-16 15:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Название")),
                (
                    "prefix",
                    models.CharField(
                        db_index=True,
                        max_length=16,
                        unique=True,
                        verbose_name="Префикс",
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(max_length=128, verbose_name="Хеш ключа"),
                ),
                (
                    "scopes",
                    models.JSONField(
                        default=list,
                        help_text="Список значений APIKeyScope.",
                        verbose_name="Области доступа",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активен"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Истекает"
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последнее использование"
                    ),
                ),
                (
                    "rate_limit",
                    models.PositiveIntegerField(
                        default=1000, verbose_name="Лимит запросов/час"
                    ),
                ),
                (
                    "organization_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "API-ключ",
                "verbose_name_plural": "API-ключи",
                "db_table": "api_keys",
                "ordering": ["-created_at"],
            },
        ),
    ]
