# Generated by Django 5.2.11 on 2026-05-16 15:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("resumes", "0001_initial"),
        ("templates_library", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoverLetter",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=255, verbose_name="slug"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("complete", "Complete"),
                            ("downloaded", "Downloaded"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured content: greeting, opening, body, closing, signature.",
                        verbose_name="content",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Display and formatting settings.",
                        verbose_name="settings",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        db_index=True,
                        default="en-us",
                        max_length=10,
                        verbose_name="language",
                    ),
                ),
                (
                    "downloads_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="downloads count"
                    ),
                ),
                (
                    "last_edited",
                    models.DateTimeField(auto_now=True, verbose_name="last edited"),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cover_letters",
                        to="resumes.resume",
                        verbose_name="matching resume",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cover_letters",
                        to="templates_library.documenttemplate",
                        verbose_name="template",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cover_letters",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "cover letter",
                "verbose_name_plural": "cover letters",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CoverLetterDownload",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("docx", "DOCX"), ("txt", "TXT")],
                        max_length=10,
                        verbose_name="format",
                    ),
                ),
                (
                    "file_url",
                    models.URLField(
                        blank=True, max_length=1024, verbose_name="file URL"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="file size (bytes)"
                    ),
                ),
                (
                    "cover_letter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="cover_letters.coverletter",
                        verbose_name="cover letter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cover_letter_downloads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "cover letter download",
                "verbose_name_plural": "cover letter downloads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CoverLetterVersion",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(verbose_name="version number"),
                ),
                (
                    "content",
                    models.JSONField(blank=True, default=dict, verbose_name="content"),
                ),
                (
                    "cover_letter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="cover_letters.coverletter",
                        verbose_name="cover letter",
                    ),
                ),
            ],
            options={
                "verbose_name": "cover letter version",
                "verbose_name_plural": "cover letter versions",
                "ordering": ["-version_number"],
            },
        ),
        migrations.AddIndex(
            model_name="coverletter",
            index=models.Index(fields=["user", "status"], name="cl_user_status_idx"),
        ),
        migrations.AddIndex(
            model_name="coverletter",
            index=models.Index(
                fields=["user", "-created_at"], name="cl_user_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="coverletter",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("user", "slug"),
                name="unique_cover_letter_slug_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="coverletterversion",
            constraint=models.UniqueConstraint(
                fields=("cover_letter", "version_number"),
                name="unique_cl_version_number",
            ),
        ),
    ]
