# Generated by Django 5.2.11 on 2026-05-16 15:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("templates_library", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExampleCategory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "name_en_us",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_en_gb",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_en_in",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_de",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_fr",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_es",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_it",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_pt_br",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_tr",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_uz",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="slug"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="description"
                    ),
                ),
                (
                    "description_en_us",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="description"
                    ),
                ),
                (
                    "description_en_gb",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="description"
                    ),
                ),
                (
                    "description_en_in",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="description"
                    ),
                ),
                (
                    "description_de",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="description"
                    ),
                ),
                (
                    "description_fr",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="description"
                    ),
                ),
                (
                    "description_es",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="description"
                    ),
                ),
                (
                    "description_it",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="description"
                    ),
                ),
                (
                    "description_pt_br",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="description"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="description"
                    ),
                ),
                (
                    "description_tr",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="description"
                    ),
                ),
                (
                    "description_uz",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="description"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Icon name (e.g. Material or FontAwesome identifier).",
                        max_length=50,
                        verbose_name="icon",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="order"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="is active"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="examples.examplecategory",
                        verbose_name="parent category",
                    ),
                ),
            ],
            options={
                "verbose_name": "example category",
                "verbose_name_plural": "example categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ResumeExample",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "title_en_us",
                    models.CharField(max_length=255, null=True, verbose_name="title"),
                ),
                (
                    "title_en_gb",
                    models.CharField(max_length=255, null=True, verbose_name="title"),
                ),
                (
                    "title_en_in",
                    models.CharField(max_length=255, null=True, verbose_name="title"),
                ),
                (
                    "title_de",
                    models.CharField(max_length=255, null=True, verbose_name="title"),
                ),
                (
                    "title_fr",
                    models.CharField(max_length=255, null=True, verbose_name="title"),
                ),
                (
                    "title_es",
                    models.CharField(max_length=255, null=True, verbose_name="title"),
                ),
                (
                    "title_it",
                    models.CharField(max_length=255, null=True, verbose_name="title"),
                ),
                (
                    "title_pt_br",
                    models.CharField(max_length=255, null=True, verbose_name="title"),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=255, null=True, verbose_name="title"),
                ),
                (
                    "title_tr",
                    models.CharField(max_length=255, null=True, verbose_name="title"),
                ),
                (
                    "title_uz",
                    models.CharField(max_length=255, null=True, verbose_name="title"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="slug"
                    ),
                ),
                (
                    "subcategory",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="subcategory",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(max_length=255, verbose_name="job title"),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="industry"
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("entry", "Entry Level"),
                            ("mid", "Mid Level"),
                            ("senior", "Senior Level"),
                        ],
                        max_length=10,
                        verbose_name="experience level",
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full resume content stored as structured JSON.",
                        verbose_name="content",
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="examples/resumes/previews/",
                        verbose_name="preview image",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="meta title",
                    ),
                ),
                (
                    "meta_title_en_us",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="meta title",
                    ),
                ),
                (
                    "meta_title_en_gb",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="meta title",
                    ),
                ),
                (
                    "meta_title_en_in",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="meta title",
                    ),
                ),
                (
                    "meta_title_de",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="meta title",
                    ),
                ),
                (
                    "meta_title_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="meta title",
                    ),
                ),
                (
                    "meta_title_es",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="meta title",
                    ),
                ),
                (
                    "meta_title_it",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="meta title",
                    ),
                ),
                (
                    "meta_title_pt_br",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="meta title",
                    ),
                ),
                (
                    "meta_title_ru",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="meta title",
                    ),
                ),
                (
                    "meta_title_tr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="meta title",
                    ),
                ),
                (
                    "meta_title_uz",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="meta title",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, default="", verbose_name="meta description"
                    ),
                ),
                (
                    "meta_description_en_us",
                    models.TextField(
                        blank=True,
                        default="",
                        null=True,
                        verbose_name="meta description",
                    ),
                ),
                (
                    "meta_description_en_gb",
                    models.TextField(
                        blank=True,
                        default="",
                        null=True,
                        verbose_name="meta description",
                    ),
                ),
                (
                    "meta_description_en_in",
                    models.TextField(
                        blank=True,
                        default="",
                        null=True,
                        verbose_name="meta description",
                    ),
                ),
                (
                    "meta_description_de",
                    models.TextField(
                        blank=True,
                        default="",
                        null=True,
                        verbose_name="meta description",
                    ),
                ),
                (
                    "meta_description_fr",
                    models.TextField(
                        blank=True,
                        default="",
                        null=True,
                        verbose_name="meta description",
                    ),
                ),
                (
                    "meta_description_es",
                    models.TextField(
                        blank=True,
                        default="",
                        null=True,
                        verbose_name="meta description",
                    ),
                ),
                (
                    "meta_description_it",
                    models.TextField(
                        blank=True,
                        default="",
                        null=True,
                        verbose_name="meta description",
                    ),
                ),
                (
                    "meta_description_pt_br",
                    models.TextField(
                        blank=True,
                        default="",
                        null=True,
                        verbose_name="meta description",
                    ),
                ),
                (
                    "meta_description_ru",
                    models.TextField(
                        blank=True,
                        default="",
                        null=True,
                        verbose_name="meta description",
                    ),
                ),
                (
                    "meta_description_tr",
                    models.TextField(
                        blank=True,
                        default="",
                        null=True,
                        verbose_name="meta description",
                    ),
                ),
                (
                    "meta_description_uz",
                    models.TextField(
                        blank=True,
                        default="",
                        null=True,
                        verbose_name="meta description",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is featured"
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="views count"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_examples",
                        to="examples.examplecategory",
                        verbose_name="category",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resume_examples",
                        to="templates_library.documenttemplate",
                        verbose_name="template",
                    ),
                ),
            ],
            options={
                "verbose_name": "resume example",
                "verbose_name_plural": "resume examples",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
    ]
