# Generated by Django 5.2.11 on 2026-05-16 15:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Redirect",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_path",
                    models.CharField(
                        db_index=True,
                        help_text="The old URL path to redirect from.",
                        max_length=500,
                        unique=True,
                        verbose_name="old path",
                    ),
                ),
                (
                    "new_path",
                    models.CharField(
                        help_text="The new URL path to redirect to.",
                        max_length=500,
                        verbose_name="new path",
                    ),
                ),
                (
                    "is_permanent",
                    models.BooleanField(
                        default=True,
                        help_text="If True, a 301 redirect is used; otherwise 302.",
                        verbose_name="permanent redirect",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
            ],
            options={
                "verbose_name": "redirect",
                "verbose_name_plural": "redirects",
                "db_table": "seo_redirect",
                "ordering": ["old_path"],
            },
        ),
        migrations.CreateModel(
            name="SEOMetadata",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        db_index=True,
                        help_text="The URL path this metadata applies to (e.g. /resume-templates/).",
                        max_length=500,
                        unique=True,
                        verbose_name="URL path",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="SEO page title (max 70 characters).",
                        max_length=70,
                        verbose_name="title",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Meta description (max 160 characters).",
                        max_length=160,
                        verbose_name="description",
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        help_text="Open Graph image for social sharing.",
                        null=True,
                        upload_to="seo/og-images/",
                        verbose_name="OG image",
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Canonical URL if this page has a preferred version.",
                        verbose_name="canonical URL",
                    ),
                ),
                (
                    "no_index",
                    models.BooleanField(
                        default=False,
                        help_text="If True, the page will include a noindex robots directive.",
                        verbose_name="no index",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO metadata",
                "verbose_name_plural": "SEO metadata",
                "db_table": "seo_metadata",
                "ordering": ["path"],
            },
        ),
    ]
