# Generated by Django 5.2.11 on 2026-05-16 15:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Уникальный идентификатор, например: ai_suggestions_v2.",
                        max_length=128,
                        unique=True,
                        verbose_name="Ключ",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_enabled",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Включён"
                    ),
                ),
                (
                    "rollout_percentage",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="0-100: доля пользователей, для которых флаг активен.",
                        verbose_name="Процент раската",
                    ),
                ),
                (
                    "whitelist",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Белый список"
                    ),
                ),
                (
                    "blacklist",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Чёрный список"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Метаданные"
                    ),
                ),
            ],
            options={
                "verbose_name": "функциональный флаг",
                "verbose_name_plural": "функциональные флаги",
                "db_table": "feature_flags",
                "ordering": ["key"],
            },
        ),
    ]
