# Generated by Django 5.2.11 on 2026-05-16 15:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "name_en_us",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_en_gb",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_en_in",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_de",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_fr",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_es",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_it",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_pt_br",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_tr",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_uz",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="slug"),
                ),
                ("bio", models.TextField(verbose_name="biography")),
                ("bio_en_us", models.TextField(null=True, verbose_name="biography")),
                ("bio_en_gb", models.TextField(null=True, verbose_name="biography")),
                ("bio_en_in", models.TextField(null=True, verbose_name="biography")),
                ("bio_de", models.TextField(null=True, verbose_name="biography")),
                ("bio_fr", models.TextField(null=True, verbose_name="biography")),
                ("bio_es", models.TextField(null=True, verbose_name="biography")),
                ("bio_it", models.TextField(null=True, verbose_name="biography")),
                ("bio_pt_br", models.TextField(null=True, verbose_name="biography")),
                ("bio_ru", models.TextField(null=True, verbose_name="biography")),
                ("bio_tr", models.TextField(null=True, verbose_name="biography")),
                ("bio_uz", models.TextField(null=True, verbose_name="biography")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="authors/",
                        verbose_name="photo",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Career Expert, CPRW"',
                        max_length=255,
                        verbose_name="title",
                    ),
                ),
                (
                    "title_en_us",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Career Expert, CPRW"',
                        max_length=255,
                        null=True,
                        verbose_name="title",
                    ),
                ),
                (
                    "title_en_gb",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Career Expert, CPRW"',
                        max_length=255,
                        null=True,
                        verbose_name="title",
                    ),
                ),
                (
                    "title_en_in",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Career Expert, CPRW"',
                        max_length=255,
                        null=True,
                        verbose_name="title",
                    ),
                ),
                (
                    "title_de",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Career Expert, CPRW"',
                        max_length=255,
                        null=True,
                        verbose_name="title",
                    ),
                ),
                (
                    "title_fr",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Career Expert, CPRW"',
                        max_length=255,
                        null=True,
                        verbose_name="title",
                    ),
                ),
                (
                    "title_es",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Career Expert, CPRW"',
                        max_length=255,
                        null=True,
                        verbose_name="title",
                    ),
                ),
                (
                    "title_it",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Career Expert, CPRW"',
                        max_length=255,
                        null=True,
                        verbose_name="title",
                    ),
                ),
                (
                    "title_pt_br",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Career Expert, CPRW"',
                        max_length=255,
                        null=True,
                        verbose_name="title",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Career Expert, CPRW"',
                        max_length=255,
                        null=True,
                        verbose_name="title",
                    ),
                ),
                (
                    "title_tr",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Career Expert, CPRW"',
                        max_length=255,
                        null=True,
                        verbose_name="title",
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Career Expert, CPRW"',
                        max_length=255,
                        null=True,
                        verbose_name="title",
                    ),
                ),
                (
                    "is_cprw_certified",
                    models.BooleanField(default=False, verbose_name="CPRW certified"),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, verbose_name="LinkedIn URL"),
                ),
                (
                    "articles_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="articles count"
                    ),
                ),
            ],
            options={
                "verbose_name": "author",
                "verbose_name_plural": "authors",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="slug"),
                ),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ArticleCategory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "name_en_us",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_en_gb",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_en_in",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_de",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_fr",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_es",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_it",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_pt_br",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_tr",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_uz",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "description_en_us",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_en_gb",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_en_in",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_de",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_fr",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_es",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_it",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_pt_br",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_ru",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_tr",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_uz",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="icon"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="order"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="is active"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="content.articlecategory",
                        verbose_name="parent category",
                    ),
                ),
            ],
            options={
                "verbose_name": "article category",
                "verbose_name_plural": "article categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "title_en_us",
                    models.CharField(max_length=255, null=True, verbose_name="title"),
                ),
                (
                    "title_en_gb",
                    models.CharField(max_length=255, null=True, verbose_name="title"),
                ),
                (
                    "title_en_in",
                    models.CharField(max_length=255, null=True, verbose_name="title"),
                ),
                (
                    "title_de",
                    models.CharField(max_length=255, null=True, verbose_name="title"),
                ),
                (
                    "title_fr",
                    models.CharField(max_length=255, null=True, verbose_name="title"),
                ),
                (
                    "title_es",
                    models.CharField(max_length=255, null=True, verbose_name="title"),
                ),
                (
                    "title_it",
                    models.CharField(max_length=255, null=True, verbose_name="title"),
                ),
                (
                    "title_pt_br",
                    models.CharField(max_length=255, null=True, verbose_name="title"),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=255, null=True, verbose_name="title"),
                ),
                (
                    "title_tr",
                    models.CharField(max_length=255, null=True, verbose_name="title"),
                ),
                (
                    "title_uz",
                    models.CharField(max_length=255, null=True, verbose_name="title"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="slug"),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Rich text content (CKEditor).",
                        verbose_name="content",
                    ),
                ),
                (
                    "content_en_us",
                    models.TextField(
                        help_text="Rich text content (CKEditor).",
                        null=True,
                        verbose_name="content",
                    ),
                ),
                (
                    "content_en_gb",
                    models.TextField(
                        help_text="Rich text content (CKEditor).",
                        null=True,
                        verbose_name="content",
                    ),
                ),
                (
                    "content_en_in",
                    models.TextField(
                        help_text="Rich text content (CKEditor).",
                        null=True,
                        verbose_name="content",
                    ),
                ),
                (
                    "content_de",
                    models.TextField(
                        help_text="Rich text content (CKEditor).",
                        null=True,
                        verbose_name="content",
                    ),
                ),
                (
                    "content_fr",
                    models.TextField(
                        help_text="Rich text content (CKEditor).",
                        null=True,
                        verbose_name="content",
                    ),
                ),
                (
                    "content_es",
                    models.TextField(
                        help_text="Rich text content (CKEditor).",
                        null=True,
                        verbose_name="content",
                    ),
                ),
                (
                    "content_it",
                    models.TextField(
                        help_text="Rich text content (CKEditor).",
                        null=True,
                        verbose_name="content",
                    ),
                ),
                (
                    "content_pt_br",
                    models.TextField(
                        help_text="Rich text content (CKEditor).",
                        null=True,
                        verbose_name="content",
                    ),
                ),
                (
                    "content_ru",
                    models.TextField(
                        help_text="Rich text content (CKEditor).",
                        null=True,
                        verbose_name="content",
                    ),
                ),
                (
                    "content_tr",
                    models.TextField(
                        help_text="Rich text content (CKEditor).",
                        null=True,
                        verbose_name="content",
                    ),
                ),
                (
                    "content_uz",
                    models.TextField(
                        help_text="Rich text content (CKEditor).",
                        null=True,
                        verbose_name="content",
                    ),
                ),
                ("excerpt", models.TextField(max_length=500, verbose_name="excerpt")),
                (
                    "excerpt_en_us",
                    models.TextField(max_length=500, null=True, verbose_name="excerpt"),
                ),
                (
                    "excerpt_en_gb",
                    models.TextField(max_length=500, null=True, verbose_name="excerpt"),
                ),
                (
                    "excerpt_en_in",
                    models.TextField(max_length=500, null=True, verbose_name="excerpt"),
                ),
                (
                    "excerpt_de",
                    models.TextField(max_length=500, null=True, verbose_name="excerpt"),
                ),
                (
                    "excerpt_fr",
                    models.TextField(max_length=500, null=True, verbose_name="excerpt"),
                ),
                (
                    "excerpt_es",
                    models.TextField(max_length=500, null=True, verbose_name="excerpt"),
                ),
                (
                    "excerpt_it",
                    models.TextField(max_length=500, null=True, verbose_name="excerpt"),
                ),
                (
                    "excerpt_pt_br",
                    models.TextField(max_length=500, null=True, verbose_name="excerpt"),
                ),
                (
                    "excerpt_ru",
                    models.TextField(max_length=500, null=True, verbose_name="excerpt"),
                ),
                (
                    "excerpt_tr",
                    models.TextField(max_length=500, null=True, verbose_name="excerpt"),
                ),
                (
                    "excerpt_uz",
                    models.TextField(max_length=500, null=True, verbose_name="excerpt"),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="articles/",
                        verbose_name="featured image",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "publish_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Leave blank for immediate publishing when status is set to published.",
                        null=True,
                        verbose_name="publish at",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=70, verbose_name="meta title"
                    ),
                ),
                (
                    "meta_title_en_us",
                    models.CharField(
                        blank=True, max_length=70, null=True, verbose_name="meta title"
                    ),
                ),
                (
                    "meta_title_en_gb",
                    models.CharField(
                        blank=True, max_length=70, null=True, verbose_name="meta title"
                    ),
                ),
                (
                    "meta_title_en_in",
                    models.CharField(
                        blank=True, max_length=70, null=True, verbose_name="meta title"
                    ),
                ),
                (
                    "meta_title_de",
                    models.CharField(
                        blank=True, max_length=70, null=True, verbose_name="meta title"
                    ),
                ),
                (
                    "meta_title_fr",
                    models.CharField(
                        blank=True, max_length=70, null=True, verbose_name="meta title"
                    ),
                ),
                (
                    "meta_title_es",
                    models.CharField(
                        blank=True, max_length=70, null=True, verbose_name="meta title"
                    ),
                ),
                (
                    "meta_title_it",
                    models.CharField(
                        blank=True, max_length=70, null=True, verbose_name="meta title"
                    ),
                ),
                (
                    "meta_title_pt_br",
                    models.CharField(
                        blank=True, max_length=70, null=True, verbose_name="meta title"
                    ),
                ),
                (
                    "meta_title_ru",
                    models.CharField(
                        blank=True, max_length=70, null=True, verbose_name="meta title"
                    ),
                ),
                (
                    "meta_title_tr",
                    models.CharField(
                        blank=True, max_length=70, null=True, verbose_name="meta title"
                    ),
                ),
                (
                    "meta_title_uz",
                    models.CharField(
                        blank=True, max_length=70, null=True, verbose_name="meta title"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="meta description"
                    ),
                ),
                (
                    "meta_description_en_us",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        null=True,
                        verbose_name="meta description",
                    ),
                ),
                (
                    "meta_description_en_gb",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        null=True,
                        verbose_name="meta description",
                    ),
                ),
                (
                    "meta_description_en_in",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        null=True,
                        verbose_name="meta description",
                    ),
                ),
                (
                    "meta_description_de",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        null=True,
                        verbose_name="meta description",
                    ),
                ),
                (
                    "meta_description_fr",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        null=True,
                        verbose_name="meta description",
                    ),
                ),
                (
                    "meta_description_es",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        null=True,
                        verbose_name="meta description",
                    ),
                ),
                (
                    "meta_description_it",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        null=True,
                        verbose_name="meta description",
                    ),
                ),
                (
                    "meta_description_pt_br",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        null=True,
                        verbose_name="meta description",
                    ),
                ),
                (
                    "meta_description_ru",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        null=True,
                        verbose_name="meta description",
                    ),
                ),
                (
                    "meta_description_tr",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        null=True,
                        verbose_name="meta description",
                    ),
                ),
                (
                    "meta_description_uz",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        null=True,
                        verbose_name="meta description",
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(blank=True, verbose_name="canonical URL"),
                ),
                (
                    "faq",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of {"question": "...", "answer": "..."} objects for FAQ schema.',
                        verbose_name="FAQ",
                    ),
                ),
                (
                    "reading_time",
                    models.PositiveIntegerField(
                        default=5, verbose_name="reading time (min)"
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="views count"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is featured"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articles",
                        to="content.articlecategory",
                        verbose_name="category",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articles",
                        to="content.author",
                        verbose_name="author",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="articles",
                        to="content.tag",
                        verbose_name="tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "article",
                "verbose_name_plural": "articles",
                "ordering": ["-publish_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "publish_at"], name="content_art_status_pub"
                    ),
                    models.Index(fields=["-created_at"], name="content_art_created"),
                    models.Index(fields=["slug"], name="content_art_slug"),
                ],
            },
        ),
    ]
