# Generated by Django 5.2.11 on 2026-05-16 15:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "name_en_us",
                    models.CharField(max_length=100, null=True, verbose_name="name"),
                ),
                (
                    "name_en_gb",
                    models.CharField(max_length=100, null=True, verbose_name="name"),
                ),
                (
                    "name_en_in",
                    models.CharField(max_length=100, null=True, verbose_name="name"),
                ),
                (
                    "name_de",
                    models.CharField(max_length=100, null=True, verbose_name="name"),
                ),
                (
                    "name_fr",
                    models.CharField(max_length=100, null=True, verbose_name="name"),
                ),
                (
                    "name_es",
                    models.CharField(max_length=100, null=True, verbose_name="name"),
                ),
                (
                    "name_it",
                    models.CharField(max_length=100, null=True, verbose_name="name"),
                ),
                (
                    "name_pt_br",
                    models.CharField(max_length=100, null=True, verbose_name="name"),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=100, null=True, verbose_name="name"),
                ),
                (
                    "name_tr",
                    models.CharField(max_length=100, null=True, verbose_name="name"),
                ),
                (
                    "name_uz",
                    models.CharField(max_length=100, null=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=120, unique=True, verbose_name="slug"
                    ),
                ),
                (
                    "skin_id",
                    models.CharField(
                        help_text='Short unique identifier, e.g. "srz4".',
                        max_length=10,
                        unique=True,
                        verbose_name="skin ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("resume", "Resume"),
                            ("cv", "CV"),
                            ("cover_letter", "Cover Letter"),
                        ],
                        db_index=True,
                        default="resume",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("professional", "Professional"),
                            ("simple", "Simple"),
                            ("modern", "Modern"),
                            ("creative", "Creative"),
                            ("business", "Business"),
                            ("classic", "Classic"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        upload_to="templates/previews/",
                        verbose_name="preview image",
                    ),
                ),
                (
                    "html_template",
                    models.TextField(
                        blank=True,
                        help_text="Path to the HTML template file.",
                        verbose_name="HTML template path",
                    ),
                ),
                (
                    "css_styles",
                    models.TextField(
                        blank=True,
                        help_text="Path to the CSS stylesheet file.",
                        verbose_name="CSS styles path",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="active"
                    ),
                ),
                (
                    "is_new",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="new"
                    ),
                ),
                (
                    "is_premium",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="premium"
                    ),
                ),
                (
                    "is_ats_friendly",
                    models.BooleanField(default=True, verbose_name="ATS friendly"),
                ),
                (
                    "popularity_score",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="popularity score"
                    ),
                ),
                (
                    "supported_sections",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of section keys this template supports.",
                        verbose_name="supported sections",
                    ),
                ),
                (
                    "color_schemes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Inline colour-scheme definitions.",
                        verbose_name="color schemes",
                    ),
                ),
                (
                    "font_options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Available font families for this template.",
                        verbose_name="font options",
                    ),
                ),
            ],
            options={
                "verbose_name": "document template",
                "verbose_name_plural": "document templates",
                "ordering": ["-popularity_score"],
            },
        ),
        migrations.CreateModel(
            name="TemplateColorScheme",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="name")),
                (
                    "primary_color",
                    models.CharField(
                        help_text="Hex colour, e.g. #3498DB.",
                        max_length=7,
                        verbose_name="primary colour",
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(max_length=7, verbose_name="secondary colour"),
                ),
                (
                    "accent_color",
                    models.CharField(max_length=7, verbose_name="accent colour"),
                ),
                (
                    "text_color",
                    models.CharField(max_length=7, verbose_name="text colour"),
                ),
                (
                    "background_color",
                    models.CharField(max_length=7, verbose_name="background colour"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="default"),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="color_scheme_set",
                        to="templates_library.documenttemplate",
                        verbose_name="template",
                    ),
                ),
            ],
            options={
                "verbose_name": "template colour scheme",
                "verbose_name_plural": "template colour schemes",
                "ordering": ["-is_default", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("template", "name"),
                        name="unique_scheme_name_per_template",
                    )
                ],
            },
        ),
    ]
