# Generated by Django 5.2.11 on 2026-05-16 15:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("templates_library", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=255, verbose_name="slug"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("complete", "Complete"),
                            ("downloaded", "Downloaded"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full resume data as JSON.",
                        verbose_name="content",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Rendering settings: color, font, spacing, margins.",
                        verbose_name="settings",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        db_index=True,
                        default="en-us",
                        max_length=10,
                        verbose_name="language",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="is primary"),
                ),
                (
                    "downloads_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="downloads count"
                    ),
                ),
                (
                    "last_edited",
                    models.DateTimeField(auto_now=True, verbose_name="last edited"),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resumes",
                        to="templates_library.documenttemplate",
                        verbose_name="template",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "resume",
                "verbose_name_plural": "resumes",
                "ordering": ["-updated_at"],
                "unique_together": {("user", "slug")},
            },
        ),
        migrations.CreateModel(
            name="ResumeDownload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("docx", "DOCX"), ("txt", "TXT")],
                        max_length=10,
                        verbose_name="format",
                    ),
                ),
                (
                    "file_url",
                    models.URLField(
                        help_text="S3 path to the generated file.",
                        max_length=1024,
                        verbose_name="file URL",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="File size in bytes.",
                        null=True,
                        verbose_name="file size",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="resumes.resume",
                        verbose_name="resume",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_downloads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "resume download",
                "verbose_name_plural": "resume downloads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResumeSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("summary", "Summary"),
                            ("experience", "Experience"),
                            ("education", "Education"),
                            ("skills", "Skills"),
                            ("languages", "Languages"),
                            ("certificates", "Certificates"),
                            ("projects", "Projects"),
                            ("awards", "Awards"),
                            ("volunteer", "Volunteer"),
                            ("hobbies", "Hobbies"),
                            ("custom", "Custom"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="section type",
                    ),
                ),
                (
                    "content",
                    models.JSONField(blank=True, default=dict, verbose_name="content"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="order"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="is visible"),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="resumes.resume",
                        verbose_name="resume",
                    ),
                ),
            ],
            options={
                "verbose_name": "resume section",
                "verbose_name_plural": "resume sections",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ResumeVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(verbose_name="version number"),
                ),
                (
                    "content",
                    models.JSONField(
                        default=dict,
                        help_text="Snapshot of resume content at this version.",
                        verbose_name="content",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="resumes.resume",
                        verbose_name="resume",
                    ),
                ),
            ],
            options={
                "verbose_name": "resume version",
                "verbose_name_plural": "resume versions",
                "ordering": ["-version_number"],
                "unique_together": {("resume", "version_number")},
            },
        ),
    ]
